version: 1
formatters:
    arlmFormatter:
        format: '%(asctime)s %(levelname)s %(message)s'
        datefmt: '%m/%d/%Y %I:%M:%S %p'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: arlmFormatter
        stream: ext://sys.stdout
    file:
        class : logging.FileHandler
        formatter: arlmFormatter
        level: DEBUG
        filename: arlm.log
loggers:
    arlmLogger:
        level: DEBUG
        handlers: [file]
        propagate: no
    consoleLogger:
        level: DEBUG
        handlers: [console]
        propagate: no

#root:
#    level: DEBUG
#    handlers: [console]
